# Generated by Django 5.2.14 on 2026-05-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
